### ISSUE TITLE
Partially wrong data returned from Multical 21

### ISSUE THREAD

**Issue by jusii** [tobiasrask/wmbus-client#5] opened 2019-07-09 08:17 UTC
Hi,

I've been using wmbus-client with node-red via node-red-contrib-wmbus-client and just realized, that the consumption values returned are correct, but status codes (dry, leak, reverse etc..) are wrong. Couple of days ago I got alert for 'dryMeter' and looked at the meter, it didn't show this code on its display. Then 2 days went and now it's reporting both Dry and reverseFlow, which both are incorrect. After that I've left water dripping for 24 hours and the meter is now reporting LEAK on its display, had no effect on data returned.

meters.json:
[
  {
    "manufacturer": "KAM",
    "serial": "76468868",
    "version": "1b",
    "deviceType": "16",
    "aes": "xxxxxxxxxxxxxxxxxxx",
    "label": "My meter"
   }
]

Running wmbus-client returns:
My meter (VolumeCold) 16, 50.507 -> 52.974 = 2.4669999999999987, delta: 0 -> 0
Info codes: Leak: false (0 hours), Dry: true (0 hours), Burst: false (0 hours), Reverse: true (0 hours)
09.07.2019,16,2d2c688846761b16,My meter (VolumeCold),50.507,50.507,0,52.974,2.4669999999999987,0

From node-red:
{"currentValue":52.972,"monthStartValue":50.507,"meterDry":true,"dryDuration":"0 hours","reverseFlow":true,"reverseDuration":"0 hours","burst":false,"burstDuration":"0 hours","leak":false,"leakDuration":"0 hours","name":"KAM"}

Then for testing purposes I tried with https://github.com/weetmuts/wmbusmeters and it returns correct values

{"media":"cold water","meter":"multical21","name":"water","id":"76468868","total_m3":52.974,"target_m3":50.507,"max_flow_m3h":0,"flow_temperature_c":7,"external_temperature_c":20,"current_status":"LEAK","time_dry":"","time_reversed":"","time_leaking":"2-3 days","time_bursting":"","timestamp":"2019-07-09T08:14:35Z"}

**Comment by tobiasrask** [comment] 2019-07-15 08:52
Hi @jusii, thank you for reporting this issue.

@sunsetdk can you check this. The problem is how to decode these values from data-frame. I haven't found any official documentation for these info bits.

**Comment by jusii** [comment] 2019-07-17 17:17
Hi, if there's anything I can do to help, just let me know. I understand it's difficult without the specs but few of those are relatively easy to trigger: Leak (ok, it takes 24h), dry and reverse. So if it's any help, I can arrange remote ssh to a linux box which has wmbus connection to multical.

**Comment by sunsetdk** [comment] 2019-07-17 17:49
Hi. I will have a look at the issue. I was wondering my self if it was working, and apparently it doesn't work. I will need to have a look at the code. I have not taken a single look at it since i created it back when the last commit was. I appriciate the offer to help. I might want some data from you if possible, I just need to look at how to get it easiest way. I think i have a debug mode hidden somewhere.

**Comment by jusii** [comment] 2019-07-17 18:34
More than happy to help, just let me know what to do.

**Comment by sunsetdk** [comment] 2019-07-18 15:13
I'm on holiday at the moment. But i can see from the wmbus-client that it is possible to get it to output the raw data to a csv file. I will need your aes key too i think, because it looks like it is raw data. Either that or i will have to create a new logging option which logs the decoded telegrams. But if you can get me the log file. It seems like you know your way round this pretty good. I will attempt to look at it ASAP. This is default storage location "./../../data/consumption-export"

**Comment by jusii** [comment] 2019-07-18 16:42
Here you go, I emailed the AES key to you:
consumption-export--20190718.log

1563465493838,23442d2c688846761b168d203d28306220884983f1aa9b5051d183dacfbcfafface9d1b4
1563465589979,23442d2c688846761b168d203e4c306220480578f75ce91fa8423ea29ff4b1513df21c3f
1563466069981,23442d2c688846761b168d2043c03062203522ba80ac521372bc537ffb11aacdb7203805
1563466165840,23442d2c688846761b168d2044d4306220a3baab7430b9966c633bf00db760dcf24aecce
1563466261653,23442d2c688846761b168d2045f8306220acab51bf72395f78fc87b6d554203cf803f26a
1563466357419,23442d2c688846761b168d20461c31622067e16c3453f89b0e84438e6ae376512208463c
1563466453139,23442d2c688846761b168d2047203162206a1584c0081a5df2bc96cb26386f5f92b4d7c7
1563466644435,23442d2c688846761b168d2049583162203f5b178a7ebf786ab9938094bd1e0271e03a04
1563466740012,23442d2c688846761b168d204a7c31622045650ded152cc7039f1b864089487a46b1a342
1563466835545,23442d2c688846761b168d204b90316220e234f88db284da76fbcbed6b59bfd2e6daa8ba
1563466931028,23442d2c688846761b168d204ca43162200cf92008a7c17b6a2d8412ac271196ddc6ba01
1563467026468,23442d2c688846761b168d204dc8316220010861b746212925d3f4d68a423238d8dd8875
1563467121857,23442d2c688846761b168d204edc316220f19ff706048e6b5fa4f6cbf0807de11e606aa8
1563467217201,23442d2c688846761b168d204ff031622065879745b690e6f1227a53d59dc90c8c3a621a
1563467312500,2a442d2c688846761b168d20501432622038cf3297e0ca15377fcd994977d98376e6ace3027b1b3a402043
1563467407749,23442d2c688846761b168d20512832622047bd22875feabaaaae7cdc9f7fd9b73dd5f69c
1563467502952,23442d2c688846761b168d20524c3262209b97694f27eb7bde855509aee5ede1db6fcabf
1563467598109,23442d2c688846761b168d205350326220869c96356637c9410c9062d98e63e763c9d7e3
1563467693217,23442d2c688846761b168d205474326220d150ec7355a5886cd8e410e2c2d8e033affd46
1563467788279,23442d2c688846761b168d20559832622035249fcded75cc42aad3a1415596b205fd59a6
1563467883294,23442d2c688846761b168d2056ac3262207fcf309b0d149e907b4b5a9370eb7f06675fc1

**Comment by sunsetdk** [comment] 2019-07-18 16:48
Do you know if this has any status codes or duration recorded?

**Comment by jusii** [comment] 2019-07-18 16:59
No status codes in above data but I think tomorrow I can arrange some logs with some status codes active.

**Comment by sunsetdk** [comment] 2019-07-20 14:55
I can see that in the data you send you have had a Leak within the last month. So the above data are fine. I have found the problem in the code (if you have starteded to generate data with in active code i would love to get them). But it seems i have found the problem in the code. Just can't work out how to fix it. JS isn't my prefered language to program in :)

**Comment by sunsetdk** [comment] 2019-07-20 15:22
I found the bug and it has been fixed. @tobiasrask can you pull the changes over and release a new version.

**Comment by sunsetdk** [comment] 2019-07-20 15:24
@jusii as the nodered version depends on my branch i think it works if you force nodered to renew its dependencies. I will change nodered to depend on Tobia's sources when he has relased the changes.

**Comment by jusii** [comment] 2019-07-20 15:40
Excellent job, looks good now! I'll test those few status codes which are easy trigger. Now I can see that I had leak this month. Thank you!

{"currentValue":58.407,"monthStartValue":50.507,"meterDry":false,"dryDuration":"0 hours","reverseFlow":false,"reverseDuration":"0 hours","burst":false,"burstDuration":"0 hours","leak":false,"leakDuration":"25-72 hours","name":"KAM"}

**Comment by tobiasrask** [comment] 2019-07-20 16:03
@sunsetdk Thank you for taking care of this issue. I will create a new release.

**Comment by tobiasrask** [comment] 2019-07-20 20:39
Pull request https://github.com/tobiasrask/wmbus-client/pull/6 is now merged to master and deployed to NPM.

Note: Unit test for `getInfoCodeDry` failed with value `false`. I fixed this by assuming that the value should now be `true`.

**Closed by tobiasrask** 2019-07-20 20:39 UTC
